# ================================================================================
# ========== WELCOME TO THE NEOCOMPILER ECO NEO BLOCKCHAIN MICROSERVICE  =========
# ================================================================================

version: "3"
services:

# ================================================================================
# ================== OPEN CONTAINER WITH NEO-CLI CONSENSUS NODES AND RPC =========
  eco-neo-csharp-node1-running:
    image: eco-neo-csharp-node:latest
    container_name: "eco-neo-csharp-node1-running"
    ports: # config1.json
      - "20333:20333"
      - "30333:30333"
    volumes:
      - ./neo-cli/configs/protocol.json:/opt/node/neo-cli/protocolNeoCompiler.json
      - ./neo-cli/configs/config1.json:/opt/node/neo-cli/config.json
      - ./neo-cli/configs/plugins/simplePolicyConfig.json:/opt/node/neo-cli/Plugins/SimplePolicy/config.json
      - ./neo-cli/configs/plugins/appLogConfig.json:/opt/node/neo-cli/Plugins/ApplicationLogs/config.json
      - ./neo-cli/configs/plugins/rpcSecurity.json:/opt/node/neo-cli/Plugins/RpcSecurity/config.json
      - ./neo-cli/wallets/wallet1.json:/opt/node/neo-cli/wallet1.json
      - ./logs-neocli-node1:/opt/node/neo-cli/Logs
#      - ./${CHAIN}:/opt/node/neo-cli/${CHAIN}
    environment:
      IS_CONSENSUS: 1
      IS_RPC: 1
      NUMBER_SERVER: 1
    cap_add:
      - NET_ADMIN
      - NET_RAW

  eco-neo-csharp-node2-running:
    image: eco-neo-csharp-node:latest
    container_name: "eco-neo-csharp-node2-running"
    ports: #config2.json
      - "20334:20334"
    volumes:
      - ./neo-cli/configs/protocol.json:/opt/node/neo-cli/protocolNeoCompiler.json
      - ./neo-cli/configs/config2.json:/opt/node/neo-cli/config.json
      - ./neo-cli/configs/plugins/simplePolicyConfig.json:/opt/node/neo-cli/Plugins/SimplePolicy/config.json
      - ./neo-cli/configs/plugins/appLogConfig.json:/opt/node/neo-cli/Plugins/ApplicationLogs/config.json
      - ./neo-cli/configs/plugins/rpcSecurity.json:/opt/node/neo-cli/Plugins/RpcSecurity/config.json
      - ./neo-cli/wallets/wallet2.json:/opt/node/neo-cli/wallet2.json
      - ./logs-neocli-node2:/opt/node/neo-cli/Logs
    environment:
      IS_CONSENSUS: 1
      IS_RPC: 0
      NUMBER_SERVER: 2
    cap_add:
      - NET_ADMIN
      - NET_RAW

  eco-neo-csharp-node3-running:
    image: eco-neo-csharp-node:latest
    container_name: "eco-neo-csharp-node3-running"
    ports: #config3.json
      - "20335:20335"
    volumes:
      - ./neo-cli/configs/protocol.json:/opt/node/neo-cli/protocolNeoCompiler.json
      - ./neo-cli/configs/config3.json:/opt/node/neo-cli/config.json
      - ./neo-cli/configs/plugins/simplePolicyConfig.json:/opt/node/neo-cli/Plugins/SimplePolicy/config.json
      - ./neo-cli/configs/plugins/appLogConfig.json:/opt/node/neo-cli/Plugins/ApplicationLogs/config.json
      - ./neo-cli/configs/plugins/rpcSecurity.json:/opt/node/neo-cli/Plugins/RpcSecurity/config.json
      - ./neo-cli/wallets/wallet3.json:/opt/node/neo-cli/wallet3.json
      - ./logs-neocli-node3:/opt/node/neo-cli/Logs
    environment:
      IS_CONSENSUS: 1
      IS_RPC: 0
      NUMBER_SERVER: 3
    cap_add:
      - NET_ADMIN
      - NET_RAW

  eco-neo-csharp-node4-running:
    image: eco-neo-csharp-node:latest
    container_name: "eco-neo-csharp-node4-running"
    ports: #config4.json
      - "20336:20336"
    volumes:
      - ./neo-cli/configs/protocol.json:/opt/node/neo-cli/protocolNeoCompiler.json
      - ./neo-cli/configs/config4.json:/opt/node/neo-cli/config.json
      - ./neo-cli/configs/plugins/simplePolicyConfig.json:/opt/node/neo-cli/Plugins/SimplePolicy/config.json
      - ./neo-cli/configs/plugins/appLogConfig.json:/opt/node/neo-cli/Plugins/ApplicationLogs/config.json
      - ./neo-cli/configs/plugins/rpcSecurity.json:/opt/node/neo-cli/Plugins/RpcSecurity/config.json
      - ./neo-cli/wallets/wallet4.json:/opt/node/neo-cli/wallet4.json
      - ./logs-neocli-node4:/opt/node/neo-cli/Logs
    environment:
      IS_CONSENSUS: 1
      IS_RPC: 0
      NUMBER_SERVER: 4
    cap_add:
      - NET_ADMIN
      - NET_RAW

  eco-neo-csharp-noderpc1-running:
    image: eco-neo-csharp-node:latest
    container_name: "eco-neo-csharp-noderpc1-running"
    ports: #config1RPC.json
      - "20337:20337"
      - "30337:30337"
    volumes:
      - ./neo-cli/configs/protocol.json:/opt/node/neo-cli/protocolNeoCompiler.json
      - ./neo-cli/configs/config1RPC.json:/opt/node/neo-cli/config.json
      - ./neo-cli/configs/plugins/simplePolicyConfig.json:/opt/node/neo-cli/Plugins/SimplePolicy/config.json
      - ./neo-cli/configs/plugins/appLogConfig.json:/opt/node/neo-cli/Plugins/ApplicationLogs/config.json
      - ./neo-cli/configs/plugins/rpcSecurity.json:/opt/node/neo-cli/Plugins/RpcSecurity/config.json
    depends_on:
      - eco-neo-csharp-node1-running
    environment:
      IS_CONSENSUS: 0
      IS_RPC: 1
      NUMBER_SERVER: 5
    cap_add:
      - NET_ADMIN
      - NET_RAW

  eco-neo-csharp-noderpc2-running:
    image: eco-neo-csharp-node:latest
    container_name: "eco-neo-csharp-noderpc2-running"
    ports: #config2RPC.json
      - "20338:20338"
      - "30338:30338"
    volumes:
      - ./neo-cli/configs/protocol.json:/opt/node/neo-cli/protocolNeoCompiler.json
      - ./neo-cli/configs/config2RPC.json:/opt/node/neo-cli/config.json
      - ./neo-cli/configs/plugins/simplePolicyConfig.json:/opt/node/neo-cli/Plugins/SimplePolicy/config.json
      - ./neo-cli/configs/plugins/appLogConfig.json:/opt/node/neo-cli/Plugins/ApplicationLogs/config.json
      - ./neo-cli/configs/plugins/rpcSecurity.json:/opt/node/neo-cli/Plugins/RpcSecurity/config.json
    depends_on:
      - eco-neo-csharp-node1-running
    environment:
      IS_CONSENSUS: 0
      IS_RPC: 1
      NUMBER_SERVER: 6
    cap_add:
      - NET_ADMIN
      - NET_RAW

# ================== OPEN CONTAINER WITH NEO-CLI CONSENSUS NODES AND RPC =========
# ================================================================================

# ================================================================================
# ================== BEGIN NEO-SCAN LIGHT WALLET INTERFACE AND POSTGRESS DB ======
  eco-neo-scan-api-running:
    image: "registry.gitlab.com/cityofzion/neo-scan/api:32259754-master"
    container_name: "eco-neo-scan-api-running"
    ports:
      - "4000:4000"
    #command: /bin/true #disable neo-scan
    environment:
      PORT: 4000
      HOST: localhost
      NEO_SEEDS: "http://eco-neo-csharp-node1-running:30333;http://eco-neo-csharp-noderpc1-running:30337;http://eco-neo-csharp-noderpc2-running:30338"
      NEO_NOTIFICATIONS_SERVER: "http://eco-neo-python-rest-running:8080/v1"
      DB_HOSTNAME: eco-neo-scan-postgresql-running
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: neoscan_prodv
      REPLACE_OS_VARS: "true"
    depends_on:
      - eco-neo-scan-postgresql-running
      - eco-neo-scan-sync-running
      - eco-neo-python-rest-running
      - eco-neo-csharp-node1-running
      - eco-neo-csharp-node2-running
      - eco-neo-csharp-node3-running
      - eco-neo-csharp-node4-running
      - eco-neo-csharp-noderpc1-running
      - eco-neo-csharp-noderpc2-running
    links:
      - eco-neo-csharp-node1-running:30333
      - eco-neo-csharp-noderpc1-running:30337
      - eco-neo-csharp-noderpc2-running:30338
      - eco-neo-scan-postgresql-running:5432

  eco-neo-scan-sync-running:
    container_name: "eco-neo-scan-sync-running"
    depends_on:
      - eco-neo-scan-postgresql-running
      - eco-neo-python-rest-running
      - eco-neo-csharp-node1-running
      - eco-neo-csharp-node2-running
      - eco-neo-csharp-node3-running
      - eco-neo-csharp-node4-running
      - eco-neo-csharp-noderpc1-running
      - eco-neo-csharp-noderpc2-running
    environment:
      NEO_NOTIFICATIONS_SERVER: "http://eco-neo-python-rest-running:8080/v1"
      NEO_SEEDS: "http://eco-neo-csharp-node1-running:30333;http://eco-neo-csharp-noderpc1-running:30337;http://eco-neo-csharp-noderpc2-running:30338"
      DB_HOSTNAME: eco-neo-scan-postgresql-running
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: neoscan_prodv
      REPLACE_OS_VARS: "true"
    image: "registry.gitlab.com/cityofzion/neo-scan/sync:32259754-master"
    links:
      - eco-neo-csharp-node1-running:30333
      - eco-neo-csharp-noderpc1-running:30337
      - eco-neo-csharp-noderpc2-running:30338
      - eco-neo-scan-postgresql-running:5432

  eco-neo-scan-postgresql-running:
    image: postgres:10.5
    container_name: "eco-neo-scan-postgresql-running"
    expose:
      - 5432
    depends_on:
      - eco-neo-csharp-node1-running
      - eco-neo-csharp-node2-running
      - eco-neo-csharp-node3-running
      - eco-neo-csharp-node4-running
      - eco-neo-csharp-noderpc1-running
      - eco-neo-csharp-noderpc2-running
      - eco-neo-python-rest-running
    environment:
      POSTGRES_DB: neoscan_prodv
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
# ================== END NEO-SCAN LIGHT WALLET INTERFACE AND POSTGRESS DB ======
# ================================================================================

# ================================================================================
# ================== BEGIN OF PYTHON CLIENT FOR RPC AND RESTFULL =================
  eco-neo-python-rest-running:
    image: eco-neo-python:latest
    container_name: "eco-neo-python-rest-running"
    ports:
      - "8080:8080"
    command: /bin/bash /opt/start_neopython_rest.sh
    environment:
      - CSHARP_NODES_CONTAINER_NAME=eco-neo-csharp-node1-running # loop until rpc curl response
    depends_on:
      - eco-neo-csharp-node1-running
      - eco-neo-csharp-node2-running
      - eco-neo-csharp-node3-running
      - eco-neo-csharp-node4-running
      - eco-neo-csharp-noderpc1-running
      - eco-neo-csharp-noderpc2-running
    volumes:
      - ./logs-neopython-rest-rpc/:/neo-python/logs
      - ./neo-python/custom-config.json:/neo-python/neo/data/protocol.privnet.json

# ================================================================================
# ===================== BEGIN TEMPORARY NOTIFICATIONS LOGGERS ====================
  eco-neo-python-logger-running:
    image: eco-neo-python:latest
    container_name: "eco-neo-python-logger-running"
    command: /bin/bash /opt/callPythonLogger.sh  #openPythonWallet.sh
    environment:
      - CSHARP_NODES_CONTAINER_NAME=eco-neo-csharp-node1-running # loop until rpc curl response
    depends_on:
      - eco-neo-csharp-node1-running
      - eco-neo-csharp-node2-running
      - eco-neo-csharp-node3-running
      - eco-neo-csharp-node4-running
      - eco-neo-csharp-noderpc1-running
      - eco-neo-csharp-noderpc2-running
    volumes:
      - ./neo-python/custom-config.json:/neo-python/neo/data/protocol.privnet.json
#      - ./logs-neopython-logger:/neo-python/logs2

# ===================== BEGIN TEMPORARY NOTIFICATIONS LOGGERS ====================
# ================================================================================

# ================================================================================
# ======================= THANKS FOR CREATING ME =================================
# ================================================================================
